name: Deploy to Deta.sh

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy to deta space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x
      # - name: Install dependencies and build
      #   run: |
      #     cd server
      #     npm install
      #     timeout -s SIGQUIT 5 npm run start
      # - name: Setup Deta.space CLI
      #   if: github.event_name == 'push'
      #   run: |
      #     cd server
      #     curl -fsSL https://get.deta.dev/space-cli.sh | sh
      #     export PATH="/home/runner/.detaspace/bin:$PATH"
      #     space login -t=${{ secrets.SPACE_ACCESS_TOKEN }}
      #     space link -i ${{ secrets.SPACE_ID }}
      #     space push -i "${{ github.event.head_commit.id }}" -t "${{ github.event.head_commit.message }}"
      # - name: prep
      #   run: cd server
      - name: Deploy
        if: github.event_name == 'push'
        uses: lizheming/deta-action@master
        with:
          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          id: ${{ secrets.SPACE_ID }}
          dir: ./server
          version: "1.0.0"
          notes: ${{ github.event.head_commit.message }}
          listed: false
